bf16: true
cutoff_len: 2048
dataset: hukum
dataset_dir: data
ddp_timeout: 180000000
do_train: true
eval_steps: 100
eval_strategy: steps
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 8
include_num_input_tokens_seen: true
learning_rate: 3.0e-05
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: Qwen/Qwen2.5-3B-Instruct
num_train_epochs: 40.0
optim: adamw_torch
output_dir: saves/Qwen2.5-3B-Instruct/lora/train_2025-04-26-07-04-11
packing: false
per_device_eval_batch_size: 8
per_device_train_batch_size: 8
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: sft
template: qwen
trust_remote_code: true
use_unsloth: true
val_size: 0.2
warmup_steps: 0
